seed: 1
dataset:
  path: 'src.datasets.MNIST'
  params:
    batch_size: 256
    shuffle: true
model:
  path: 'src.ff.models.FFClassifier'
  params:
    in_features: 784
    hidden_layers: 4
    hidden_units: 784
    activation:
      path: 'torch.nn.ReLU'
    dropout: 0.2
    threshold: 2.0
    optimiser:
      path: 'torch.optim.Adam'
    learning_rate: 0.001
  location: 'models/model.pt'
trainer:
  path: 'src.ff.trainers.GreedyTrainer'
  params:
    epochs: 5
tester:
  path: 'src.ff.testers.Tester'
wandb:
  project: "forward-forward"
  entity: "arneschreuder"