seed: 1
dataset:
  path: 'src.datasets.MNIST'
  params:
    batch_size: 32
    shuffle: true
model:
  path: 'src.ff.models.FFClassifier'
  params:
    in_features: 784
    hidden_layers: 4
    hidden_units: 2000
    activation:
      path: 'torch.nn.LeakyReLU'
    dropout: 0.2
    threshold: 2.0
    optimiser:
      path: 'torch.optim.Adam'
    learning_rate: 0.001
trainer:
  path: 'src.ff.trainers.GreedyTrainer'
  params:
    epochs: 10
wandb:
  project: "forward-forward"
  entity: "arneschreuder"